name = "Miners Online Base Server"
author = "samuelh2005"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27fe3e17ee542642a69e047163abcca55e7cd081e836b8e4d35de195e770a8e3"

[versions]
fabric = "0.19.5"
minecraft = "26.3"
